### ISSUE TITLE
Compact mode

### ISSUE THREAD

**Issue by skanderm** [dangwu/8chen#1]
Hi Dan, I appreciate the work you’ve done!

Any chance you can add a compact mode option? I preferred the list without thumbnails.

**Comment by dangwu** [comment]
Thanks! That's a good idea. I'll add it to my TODO list. Shouldn't take too long.

**Comment by jontayesp** [comment]
This is the only thing holding me back from using 8chen. Would love an option to remove thumbnails. Thanks!

**Comment by dangwu** [comment]
Version 1.3 released today has a new 'Compact Mode' in the settings. When enabled this will remove the thumbnails. Thanks for the suggestions!
